<h2  align="center"> Lab 7_Linear Regression Multiple Variables</h2>

<h3 style="color:purple">Sample problem of predicting home price in monroe, new jersey (USA)</h3>

Below is the table containing home prices in monroe twp, NJ. Here price depends on **area (square feet), bed rooms and age of the home (in years)**. Given these prices we have to predict prices of new homes based on area, bed rooms and age.

<img src="homeprices.jpg" style='height:200px;width:350px'>

Given these home prices find out price of a home that has,

**3000 sqr ft area, 3 bedrooms, 40 year old**

**2500 sqr ft area, 4 bedrooms,  5 year old**

We will use regression with multiple variables here. Price can be calculated using following equation,

<img src="equation.jpg" >

Here area, bedrooms, age are called independant variables or **features** whereas price is a dependant variable

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('house_dataset.csv')
df

Area   Bedrooms   Age   Price
0   1124          3    25  197400
1   2440          2    29  289000
2   2873          3    27  362300
3   1196          1    10  239600
4   1828          3     1  387800
..   ...        ...   ...     ...
95  1592          1     2  319200
96  1489          3    14  288900
97  2737          3     7  448700
98  1564          1    19  231400
99  2886          2    15  403600

[100 rows x 4 columns]

In [3]:
new_df = df.drop(' Price',axis='columns')
new_df

Area   Bedrooms   Age
0   1124          3    25
1   2440          2    29
2   2873          3    27
3   1196          1    10
4   1828          3     1
..   ...        ...   ...
95  1592          1     2
96  1489          3    14
97  2737          3     7
98  1564          1    19
99  2886          2    15

[100 rows x 3 columns]

In [4]:
price = df[' Price']
price

0     197400
1     289000
2     362300
3     239600
4     387800
       ...  
95    319200
96    288900
97    448700
98    231400
99    403600
Name:  Price, Length: 100, dtype: int64

In [5]:
reg = linear_model.LinearRegression()
reg.fit(new_df,price)

LinearRegression()

In [6]:
reg.coef_

array([  100., 20000., -5000.])

In [7]:
reg.intercept_

149999.9999998961

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [8]:
reg.predict([[3000, 3, 40]])

C:\Users\AbdulAziz\anaconda3\envs\tf\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([310000.00000005])

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [9]:
reg.predict([[2500, 4, 5]])

C:\Users\AbdulAziz\anaconda3\envs\tf\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([455000.00000002])

<center><h1> Happy Learning